---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
      ver: latest
  template: 
    metadata:
      labels:
        app: testapp
        ver: latest
    spec:
      containers:
        - name: testapp
          image: docker pull 90188/rishi:latest
          ports:
            - containerPort: 80
              protocol: TCP